#ifndef TENNIS_SCORER_H
#define TENNIS_SCORER_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define PLAYER_1 1

#define PLAYER_2 2

#define GAME_STATE_PLAYING 0

#define GAME_STATE_DEUCE 1

#define GAME_STATE_ADVANTAGE_P1 2

#define GAME_STATE_ADVANTAGE_P2 3

#define GAME_STATE_COMPLETED 4

/**
 * Opaque handle to a tennis match with history
 */
typedef struct TennisMatch TennisMatch;

/**
 * C-compatible score representation
 */
typedef struct MatchScore {
  uint8_t player1_sets;
  uint8_t player2_sets;
  uint8_t player1_games;
  uint8_t player2_games;
  uint8_t player1_points;
  uint8_t player2_points;
  uint8_t game_state;
  bool is_tiebreak;
  uint8_t winner;
  uint8_t deuce_count;
} MatchScore;

/**
 * C-compatible point event with timestamp
 */
typedef struct PointEvent {
  uint8_t player;
  double timestamp;
} PointEvent;

/**
 * Create a new match with default settings (Best-of-3, Ad scoring, 7-point tiebreak)
 */
struct TennisMatch *tennis_match_new_default(void);

/**
 * Create a new Best-of-5 match
 */
struct TennisMatch *tennis_match_new_best_of_5(void);

/**
 * Create a new No-Ad scoring match (Best-of-3)
 */
struct TennisMatch *tennis_match_new_no_ad(void);

/**
 * Create a new match with custom settings
 */
struct TennisMatch *tennis_match_new_custom(uint8_t sets_to_win,
                                            uint8_t tiebreak_points,
                                            bool final_set_tiebreak,
                                            bool no_ad_scoring);

/**
 * Free a match. Safe to call with null.
 */
void tennis_match_free(struct TennisMatch *match_ptr);

/**
 * Score a point for the given player (PLAYER_1 or PLAYER_2).
 * Returns false if match_ptr is null or player is invalid.
 */
bool tennis_match_score_point(struct TennisMatch *match_ptr, uint8_t player);

/**
 * Undo the last point. Returns false if match_ptr is null.
 */
bool tennis_match_undo(struct TennisMatch *match_ptr);

/**
 * Get the current score. Returns zeroed MatchScore if match_ptr is null.
 */
struct MatchScore tennis_match_get_score(const struct TennisMatch *match_ptr);

/**
 * Check if undo is available. Returns false if match_ptr is null.
 */
bool tennis_match_can_undo(const struct TennisMatch *match_ptr);

/**
 * Check if the match is complete. Returns false if match_ptr is null.
 */
bool tennis_match_is_complete(const struct TennisMatch *match_ptr);

/**
 * Get the winner (PLAYER_1, PLAYER_2, or 0 if no winner yet).
 * Returns 0 if match_ptr is null.
 */
uint8_t tennis_match_get_winner(const struct TennisMatch *match_ptr);

/**
 * Get the number of point events recorded in the match.
 * Returns 0 if match_ptr is null.
 */
uint32_t tennis_match_get_point_count(const struct TennisMatch *match_ptr);

/**
 * Fill a caller-provided buffer with point events.
 * Returns false if match_ptr or buffer is null, or buffer_size is too small.
 */
bool tennis_match_get_points(const struct TennisMatch *match_ptr,
                             struct PointEvent *buffer,
                             uint32_t buffer_size);

#endif  /* TENNIS_SCORER_H */
